name: Build & Deploy Spring app

on:
    push:
     branches:
        - master

jobs:
    build-deploy:
        name: Build and Deploy Spring boot for beginner
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: 17
            
            - name: unit Tests
              run: mvn -B test --file index.html
              
            - name: Build the application
              run: |
                mvn clean
                mvn -B package --file index.html

            

            


        
